[package]
name = "rocketrustvuejs3"
version = "0.1.0"
authors = ["Antoine Boucher <antoine.bou13@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "main"
path = "backend/main.rs"

[dependencies]
rocket = "0.4.7"
rocket_codegen = "0.4.2"
serde = "1.0.99"
serde_derive = "1.0.99"
serde_json = "1.0.40"
rocket_cors = "0.4.0"
