[package]
name = "rocketrustvuejs3"
version = "0.1.0"
authors = ["Antoine Boucher <antoine.bou13@gmail.com>"]
edition = "2018"

[[bin]]
name = "main"
path = "backend/main.rs"

[lib]
name = "lib"
path = "backend/lib/lib.rs"

[dependencies]
rocket = { version = "0.4.7", features = ["tls"] }
rocket_contrib = {version="0.4.5", features=["json", "tera_templates"]}
rocket_codegen = "0.4.2"
serde = "1.0.99"
serde_derive = "1.0.99"
serde_json = "1.0.40"
rocket_cors = "0.4.0"
chrono = "0.4"
diesel = { version = "1.4.4", features = ["postgres"] }
dotenv = "0.15.0"
rust-crypto = "^0.2"
rand = "0.7.3"
tera = "1"
