  
version: '3.8'
services:
    dashercontrol:
        build: .
        container_name: v
        ports:
            - 8080:8080
        volumes:
            - ./src:/usr/src/app
         links:
             - database
     database:
         image: postgres
         container_name: dashercontrol_db
         hostname: dashercontrol_db
         expose:
             - 5432
         volumes:
             - pgdata:/var/lib/postgresql/data/pgdata
         environment:
             POSTGRES_PASSWORD: root   # put your superuser database password this here
             POSTGRES_USER: postgres
             POSTGRES_DB: diesel
             PGDATA: /var/lib/postgresql/data/pgdata


volumes:
    pgdata: {}