[global]
template_dir = "frontend/dist/templates"

[development]
address = "0.0.0.0"
port = 8080
# workers = [number of cpus * 2]
keep_alive = 5
read_timeout = 5
write_timeout = 5
log = "normal"
# secret_key = [randomly generated at launch]
limits = { forms = 32768 }

[staging]
address = "0.0.0.0"
port = 9081
# workers = [number of cpus * 2]
keep_alive = 5
read_timeout = 5
write_timeout = 5
log = "normal"
# secret_key = [randomly generated at launch]
limits = { forms = 32768 }

[production]
address = "0.0.0.0"
port = 8081
#workers = [number of cpus * 2]
keep_alive = 5
read_timeout = 5
write_timeout = 5
log = "critical"
#secret_key = [randomly generated at launch]
limits = { forms = 32768 }
tls = { certs = "certs/cert.crt", key = "certs/cert.key" }


[global.databases]
postgres_db = { url = "postgres://postgres:root@localhost/diesel" }

