DROP TABLE tenants;

CREATE TABLE tenants (
  id SERIAL PRIMARY KEY,
  email VARCHAR NOT NULL,
  name VARCHAR NOT NULL,
  username VARCHAR NOT NULL,
  password VARCHAR NOT NULL,
  tenant_role VARCHAR NOT NULL
)