# This is a basic workflow to help you get started with Actions

name: test

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
#   push:
#     branches: [ main ]
#   pull_request:
#     branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout branch
        uses: actions/checkout@v2
        
      - name: Install ubuntu Dependencies
        run: sudo apt-get install cmake make g++ build-essential libpq-dev libssl-dev
    
      - name: Install rust
        run: bash scripts/rust-setup-dev.sh
      
      - name: use default .env file
        run: source .env
          
      - name: Run cargo build
        continue-on-error: true
        run: RUSTC_WRAPPER=sccache cargo test
